name: build

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]    
    steps:
    
    - name: Checkout GitBucket repo
      uses: actions/checkout@v2
      with:
        repository: gitbucket/gitbucket
        path: gitbucket

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Run tests
      run: |
        cd gitbucket
        sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test
      
    - name: Build executable
      run: |
        cd gitbucket
        sbt executable
      
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        path: docker
    
    - name: Build docker
      run: |
        mv gitbucket/target/executable/gitbucket.war docker/gitbucket.war
        cd docker
        docker build . --file Dockerfile-nightly --tag gitbucket/gitbucket:nightly
        
    - name: Push to Github Package Registry
      run: |
        docker login -u gitbucket -p ${{ secrets.DOCKER_PASSWORD }}
        docker push gitbucket/gitbucket:nightly